services:
  evescout:
    build: .
    container_name: eve-scout-webhook

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
